# Generated by Django 5.1.3 on 2026-08-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_feed', models.CharField(max_length=255)),
                ('original_alert_text', models.TextField()),
                ('source_timestamp', models.DateTimeField()),
                ('validation_loops_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=50)),
                ('generated_markdown_report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_intelligence_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
